# Generated by Django 4.0.5 on 2022-07-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0007_alter_category_menu_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=31)),
                ('slug', models.SlugField(max_length=15)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TodaySpecialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': "Продукт 'speacial today'",
                'verbose_name_plural': "Продукты 'speacial today'",
            },
        ),
    ]
