# Generated by Django 4.0.6 on 2022-08-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todayspecialproduct',
            options={'ordering': ['-date'], 'verbose_name': "Продукт 'speacial today'", 'verbose_name_plural': "Продукты 'speacial today'"},
        ),
    ]
