# Generated by Django 4.0.6 on 2022-08-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
