# Generated by Django 4.0.5 on 2022-06-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_menu_order_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='menu_order',
            field=models.IntegerField(unique=True),
        ),
    ]
