# Generated by Django 4.0.5 on 2022-07-04 14:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_alter_category_menu_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('shipping_price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Доступный город',
                'verbose_name_plural': 'Доступные города',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderProdcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'verbose_name': 'Продукт из заказа',
                'verbose_name_plural': 'Продукты из заказов',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=127)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введён в формате: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('shipping_price', models.IntegerField()),
                ('cart_total', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('shipping_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.availablecity')),
            ],
            options={
                'verbose_name': 'Детали Заказа',
                'verbose_name_plural': 'Детали Заказов',
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'verbose_name': 'Продукт из корзины',
                'verbose_name_plural': 'Продукты из корзины',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.IntegerField(default=0)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('shipping_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.availablecity')),
            ],
            options={
                'verbose_name': 'Детали Корзины',
                'verbose_name_plural': 'Детали Корзин',
                'ordering': ['cart_total'],
            },
        ),
    ]
