# Generated by Django 4.0.5 on 2022-07-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_category_menu_order'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProdcut',
            new_name='OrderProduct',
        ),
    ]
