# Generated by Django 4.0.5 on 2022-07-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetails',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartdetails',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartDetails',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
