# Generated by Django 4.0.5 on 2022-07-16 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartdetails_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
