# Generated by Django 4.0.7 on 2022-08-04 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=127, null=True)),
                ('table_size', models.CharField(choices=[('Table Size', 'Table Size'), ('2F - 3F', '2F - 3F'), ('2.5F - 3.5F', '2.5F - 3.5F'), ('3F - 4F', '3F - 4F'), ('3.5F - 4.5F', '3.5F - 4.5F'), ('5F - 6F', '5F - 6F'), ('5.5F - 6.5', '5.5F - 6.5F')], default='Table Size', max_length=31, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
